### ISSUE TITLE
Open make crash guide too fast

### ISSUE THREAD

**Issue by mac4kent** [alexzielenski/Mousecape#118] opened 2020-05-07 12:36 UTC
May 7, 2020
Mousecape 0.0.6 make crash guide too fast while open.
Catalina
10.15.5 Beta (19F72f)
.......................................

Process:               Mousecape [1151]
Path:                  /Applications/Mousecape.app/Contents/MacOS/Mousecape
Identifier:            com.alexzielenski.Mousecape
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Mousecape [1151]
User ID:               501

Date/Time:             2020-05-07 05:35:45.187 -0700
OS Version:            Mac OS X 10.15.5 (19F72f)
Report Version:        12
Anonymous UUID:        321431BF-5F9F-227D-B421-E4C007C21C3D

Time Awake Since Boot: 1300 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000100e1e000-0000000100e4c000 [  184K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   @                          	0x000000010433e000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeeede1c00
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010433e000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x100e1e000 -        0x100e4bff7 +@ (0) <E8388370-844D-3E9A-AE8E-A019835AA96F> @
       0x10433d000 -        0x1043ceeff +@ (750.5) <E8B6E53C-ACAE-3739-B5FF-FB9EF4BBAB41> @

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 991
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1040K resident=0K(0%) swapped_out_or_unallocated=1040K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             280K        3 
__DATA_CONST                        20K        1 
__LINKEDIT                         272K        2 
__TEXT                             768K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.3M       12 

Model: iMac18,3, BootROM 181.0.0.0.0, 4 processors, Quad-Core Intel Core i5, 3.5 GHz, 16 GB, SMC 2.41f2
Graphics: kHW_AMDRadeonPro575Item, Radeon Pro 575, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR4 SO-DIMM, 2400 MHz, 0x80AD, 0x484D413831475336414652384E2D554820202020
Memory Module: BANK 1/DIMM0, 8 GB, DDR4 SO-DIMM, 2400 MHz, 0x80AD, 0x484D413831475336414652384E2D554820202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x16F), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1610.1)
Bluetooth: Version 7.0.5f3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: iPad, Ethernet, en4
USB Device: USB 3.0 Bus
USB Device: iPad
USB Device: Afterglow Gamepad for Xbox 360
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
Thunderbolt Bus: iMac, Apple Inc., 41.4

**Comment by luckydonald** [comment] 2020-05-13 12:10
For macOS 10.14 (Mojave) and later, check #119 for a workaround.

**Comment by mac4kent** [comment] 2020-05-14 15:59
Oh well there make bad crash while Catalina MacOS 10.15.5 beta see picture 
![1  MacOS 10 15 5 beta](https://user-images.githubusercontent.com/4253305/81957265-3645eb00-95c1-11ea-8560-bded5569be43.png)

**Comment by lmaoguy123** [comment] 2020-05-29 08:57
Hey, its happen to me too, so i use version 0.0.5

**Comment by alexzielenski** [comment] 2020-06-13 23:21
Duplicate of #116 and #119

This was an issue with my erroneous uploading a build that was ad-hoc codesigned. Build 1813 should pass this check properly.

https://github.com/alexzielenski/Mousecape/releases/tag/1813

**Closed by alexzielenski** 2020-06-13 23:21 UTC

**Comment by mac4kent** [comment] 2020-06-14 01:41
Thank you for fix everything great.
