### ISSUE TITLE
Windows .ani files to mousecape files

### ISSUE THREAD

**Issue by andrewt1738** [alexzielenski/Mousecape#91] opened 2018-05-16 23:55 UTC
Is there any easy way to convert a windows animated cursor file (.ani) into the vertically stacked file needed by mousecape?

**Comment by Anais-Et-Vous** [comment] 2019-01-05 04:07
try using xnviewmp https://www.xnview.com/en/xnviewmp/ free software to convert common windows images... you can use "multipage output" for .ani files and drag the set onto mousecape directly :) its invaluable software to me! enjoy :)

**Comment by KICKFLIP85** [comment] 2019-06-21 22:32
Sorry for being very very very very late on this, but can someone give me a tutorial on turning .ani files to the vertically stacked files (preferably doing this in batches instead of one by one)? I can't take going to one website and converting it and then going to another to convert it again D:

**Comment by alexzielenski** [comment] 2019-10-13 19:56
Unfortunately I have no expertise with ani files whatsoever. I do know that with Mousecape it is sufficient to use a free photo editor to stack your frames, though.

Closing this since it is a support request and not a bug report.

**Closed by alexzielenski** 2019-10-13 19:56 UTC
